[supervisord]
nodaemon=true

[program:xvfb]
command=/usr/bin/Xvfb :0 -screen 0 1920x1080x24
priority=1
autorestart=true

[program:xfce]
command=/usr/bin/startxfce4
environment=DISPLAY=:0
priority=2
autorestart=true

[program:x11vnc]
command=/usr/bin/x11vnc -display :0 -forever -nopw
priority=3
autorestart=true

[program:novnc]
command=/usr/share/novnc/utils/novnc_proxy --vnc localhost:5900 --listen 8080
priority=4
autorestart=true